server:
  port: 8080

spring:
  application:
    name: "bookstore"
  devtools:
    add-properties: false
  profiles:
    active: default

adapters:
  postgres:
    database: "bookstore_iw3k"
    schema: "bookstore"
    username: "bookstore_iw3k_user"
    password: "ve9EPe42ynzbTPh99GhjDYIHvGKDEGSe"
    host: "dpg-cne8pt8l5elc73f52i50-a.oregon-postgres.render.com"
    port: 5432

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

#logging:
#  level:
#    io.r2dbc: DEBUG
